DEBUG = True
ASSETS_DEBUG = False
APP_NAME = 'OCCRP Search'

ELASTICSEARCH_HOST = '127.0.0.1:9200'
ELASTICSEARCH_INDEX = 'graph'
SOURCE_DOC_TYPE = 'source'

SQLALCHEMY_DATABASE_URI = 'postgresql://localhost/loom'
